### ISSUE TITLE
UI: Style This Web App

### ISSUE THREAD

**Issue by pooja-gera** [pooja-gera/algorithm-finder#1]
Hello engineers, 

Feel free to take a shot at making this web app prettier. 
I have just two simple asks: 

1. It should be minimalistic.
2. The web app should be responsive. 

While you are asking to get assigned to this issue, please add a Figma mockup screenshot of the redesign you're thinking so that it becomes easier for me to assign you the issue 😎

**Comment by Tanisha-Verma-16** [comment]
I'd like to redesign the app, Here's my figma mockup [https://www.figma.com/proto/VEwIhwba6MrUc1pKSSc9ox/AlgoFinder-UI?node-id=5-84&t=puIrUXQdevfwLreU-1](mockup)

**Comment by Tanisha-Verma-16** [comment]
here's my mockup https://www.figma.com/proto/VEwIhwba6MrUc1pKSSc9ox/AlgoFinder-UI?node-id=5-84&t=puIrUXQdevfwLreU-1

**Comment by pooja-gera** [comment]
Hey Tanisha, 
I really like the interactions and what you've added for the description of each question. 
Here are a couple suggestions: 

1. Let the background color be white. 
2. Buttons / primary colors - make them all black (https://ui.shadcn.com/ here is the reference, you don't need to use shadcn components, but just look how premium and professional a white background and just black as the primary color looks)
3. We don't need to use all caps anywhere
4. For the logo, use this emoji 👾
5. Dark / Light mode support is not needed 
6. Navbar just needs Login / Signup, nothing else 
7. Padding for all buttons should be uniform, they should be rectangular (width > height), examples of paddings could be `8px 24px 8px 24px` `16px 40px 16px 40px` etc. 
8. The card where we have the questions, make sure the border-radius is in line with the border-radius of the buttons. Currently the buttons have too-much roundness, and the card has too less. You can inspect any button on shadcn ui to see what padding / border-radius ratio they are using. 

Thankyou soo much for putting such an amazing effort, I am assigning this issue to you now, happy open source month to you! 🥳

**Comment by Tanisha-Verma-16** [comment]
Sure! Thankyou

**Comment by Tanisha-Verma-16** [comment]
Hey... Just wanted to confirm, when you said that all the buttons should be black does that include the yes and no button too? Btw here is what I have so far
![Screenshot 2024-10-08 210343](https://github.com/user-attachments/assets/e8583c5c-600d-4b39-aabf-e9ee25f0361a)

**Comment by pooja-gera** [comment]
The colors you have right now are just perfect! You're right, Yes and No don't need to be black, they look good in Green and Red

**Comment by Tanisha-Verma-16** [comment]
Okk, then i will make my PR
