### ISSUE TITLE
Back and Restart Button Not Needed Together

### ISSUE THREAD

**Issue by pooja-gera** [pooja-gera/algorithm-finder#11]
When end of control is reached, there should not be `Back` and `Restart` options together, only `Restart`

<img width="1440" alt="Screenshot 2024-10-10 at 1 42 00 PM" src="https://github.com/user-attachments/assets/351bff2c-d745-4a2e-9920-b48047146583">

**Comment by Fixito** [comment]
Hi! I would like to work on this issue. Can you assign it to me ?

**Comment by Tanisha-Verma-16** [comment]
Please Assign this issue to me

**Comment by pooja-gera** [comment]
Hello @Fixito this issue was an enhancement on top of something @Tanisha-Verma-16 was already working on, please feel free to open a new issue, I'll also add some more issues to this repo today, have a look at it and if something is up your alley, do contribute ^.^
