### ISSUE TITLE
Add Google OAuth and Number of Visitors

### ISSUE THREAD

**Issue by pooja-gera** [pooja-gera/algorithm-finder#2]
Hello engineers, 

If you're looking to try adding OAuth to a small application, this is a good place to start. Please add authentication via Google only for now. Feel free to use a database of your choice for storing user data and the number of visitors for algorithm-finder 🎀

1. The number of visitors should be displayed at the footer of the web app. 
2. The name and profile picture of the user should be displayed on the top-right corner in the header of the web app.

**Comment by gargantuadev** [comment]
Hello there! 
May you kindly assign this issue to me?

**Comment by pooja-gera** [comment]
Sure, have fun contributing, please feel free to ask if you have any questions at any point. 
Happy Open Source month to you! 🥳

**Comment by gargantuadev** [comment]
Hello @pooja-gera! 
I made a PR for it (#6) 🚀
