### ISSUE TITLE
Optimization: Visit every node in path once

### ISSUE THREAD

**Issue by Ananya-Bhardwaj** [pooja-gera/algorithm-finder#3]
The current code traverses the tree to look for a node from the root each time, instead since the next node will always be either the left or the right node, the time complexity can be reduced from O(k^2) to O(k), 
where k is the number of nodes in the current path

**Comment by pooja-gera** [comment]
Please feel free to work on it, happy open source month to you! 🥳

**Comment by Ananya-Bhardwaj** [comment]
Thank you :)
