### ISSUE TITLE
Add Back Button to Navigate to Previous Question

### ISSUE THREAD

**Issue by Tanisha-Verma-16** [pooja-gera/algorithm-finder#9]
I'd like to propose adding a **Back button** that allows users to navigate to the previous question in the decision tree. Currently, users can only move forward (Yes/No) without the ability to go back.

Proposed Solution:

- Add a "Back" button to return to the last question.
- The button should be hidden or disabled on the first question.
- Ensure that previous selections are retained when navigating back.

This would improve user experience by providing more control over the flow of questions. Happy to work on this if approved!

**Comment by pooja-gera** [comment]
Yes this sounds like a fun idea, please go ahead!
